[project]
name = "leal-transcription"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Swellshinider", email = "eduardoleal.contact@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "faster-whisper",
    "pyperclip",
    "nvidia-cublas-cu12",
    "nvidia-cudnn-cu12>=9,<10",
]

[project.scripts]
transcribe = "leal_transcription.cli:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
